#!/usr/bin/env bash
set -euo pipefail

qa_info() { echo "[INFO] $*"; }
qa_warn() { echo "[WARN] $*"; }
qa_error() { echo "[ERROR] $*"; }

qa_repo_root() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
  cd "$script_dir/../../../.." && pwd -P
}

qa_binary_path() {
  local root
  root="$(qa_repo_root)"
  echo "$root/core/target/release/agent-orchestrator"
}

qa_require_binary() {
  local bin
  bin="$(qa_binary_path)"
  if [[ ! -x "$bin" ]]; then
    qa_error "Binary not found: $bin"
    qa_error "Build it with: (cd core && cargo build --release)"
    exit 2
  fi
}

qa_parse_common_args() {
  QA_OUTPUT_JSON=0
  QA_WORKSPACE=""
  QA_PROJECT=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --workspace)
        QA_WORKSPACE="$2"
        shift 2
        ;;
      --project)
        QA_PROJECT="$2"
        shift 2
        ;;
      --json)
        QA_OUTPUT_JSON=1
        shift
        ;;
      -h|--help)
        return 1
        ;;
      *)
        qa_error "Unknown argument: $1"
        return 1
        ;;
    esac
  done

  export QA_OUTPUT_JSON QA_WORKSPACE QA_PROJECT
}

qa_print_usage() {
  cat <<'USAGE'
Usage:
  <script>.sh [--workspace <workspace-id>] [--project <project-id>] [--json]

Options:
  --workspace <workspace-id>  Workspace ID used for task creation.
  --project <project-id>      Project ID used for task creation (default: auto-generated).
  --json                      Print machine-readable summary JSON.
USAGE
}

qa_extract_task_id() {
  local create_output="$1"
  echo "$create_output" | grep -oE '[0-9a-f-]{36}' | head -1
}

qa_resolve_project() {
  local prefix="${1:-qa}"
  if [[ -z "${QA_PROJECT:-}" ]]; then
    QA_PROJECT="${prefix}-$(date +%s)-$RANDOM"
  fi
  if [[ -z "${QA_WORKSPACE:-}" ]]; then
    QA_WORKSPACE="${QA_PROJECT}-ws"
  fi
  export QA_PROJECT QA_WORKSPACE
}

qa_prepare_project() {
  local workflow="$1"
  local bin
  local root
  local sample_dir
  local project_root
  bin="$(qa_binary_path)"
  project_root="workspace/$QA_PROJECT"
  "$bin" qa project create "$QA_PROJECT" \
    --workspace "$QA_WORKSPACE" \
    --workflow "$workflow" \
    --root-path "$project_root" \
    --qa-target "docs/qa" \
    --ticket-dir "docs/ticket" \
    --force >/dev/null
  root="$(qa_repo_root)"
  sample_dir="$root/$project_root/docs/qa"
  mkdir -p "$sample_dir"
  cat >"$sample_dir/qa-smoke.md" <<'EOF'
# QA Smoke

This file is auto-generated by QA script helpers to keep project-local target discovery non-empty.
EOF
}

qa_reset_project_data() {
  local bin
  local root
  local project_root
  bin="$(qa_binary_path)"
  root="$(qa_repo_root)"
  project_root="$root/workspace/$QA_PROJECT"
  "$bin" qa project reset "$QA_PROJECT" --keep-config --force >/dev/null
  rm -rf "$project_root/docs/ticket" "$project_root/docs/qa"
  mkdir -p "$project_root/docs/qa" "$project_root/docs/ticket"
}
