# typed: false
# frozen_string_literal: true

# Formula generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Orchestrator < Formula
  desc "AI-native SDLC automation — agent orchestrator CLI and daemon"
  homepage "https://github.com/c9r-io/orchestrator"
  version "PLACEHOLDER_VERSION"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/vPLACEHOLDER_VERSION/orchestrator-vPLACEHOLDER_VERSION-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_MACOS_ARM64"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/c9r-io/orchestrator/releases/download/vPLACEHOLDER_VERSION/orchestrator-vPLACEHOLDER_VERSION-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/vPLACEHOLDER_VERSION/orchestrator-vPLACEHOLDER_VERSION-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "orchestrator"
    bin.install "orchestratord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/orchestrator --version")
  end
end
