#!/bin/sh
# Auto-generated by orchestrator — daemon PID guard for agent subprocesses.
# Reads Claude Code hook JSON from stdin, checks if the Bash command would
# kill the orchestrator daemon, and blocks it if so.
DAEMON_PID="99299"
INPUT=$(cat)
COMMAND=$(printf '%s' "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/^"command"[[:space:]]*:[[:space:]]*"//;s/"$//')
if [ -z "$COMMAND" ]; then
  printf '{"continue":true}\n'
  exit 0
fi
# Check for kill patterns targeting the daemon PID or orchestratord
case "$COMMAND" in
  *kill*"$DAEMON_PID"*|*pkill*orchestratord*|*killall*orchestratord*|*kill*daemon.pid*|*orchestrator*daemon*stop*)
    printf '{"continue":false,"stopReason":"BLOCKED: command would kill orchestrator daemon (PID %s). Self-referential safety violation."}\n' "$DAEMON_PID"
    exit 2
    ;;
esac
printf '{"continue":true}\n'
exit 0
