#!/usr/bin/env ruby
# frozen_string_literal: true

# FR-155: derive the public skill inventory and validate filesystem references
# taught by the authoritative SKILL.md corpus.

require "json"
require "pathname"
require "shellwords"
require "yaml"

ROOT_NAMES = %w[
  AGENTS.md CLAUDE.md SKILLS.md Cargo.toml Makefile package.json
  docker-compose.yml
].freeze
ROOT_PREFIXES = %w[
  .agents .claude .cursor .github config core crates data deploy docker docs
  fixtures gui k8s portal scripts site test-yaml-warnings workspace
].freeze
SKILL_PREFIXES = %w[assets references scripts].freeze
SHELL_FENCES = %w[bash console sh shell zsh].freeze
SCOPES = %w[repo skill-relative template output companion].freeze
GLOB_CHARS = /[*?\[\]]/

Candidate = Struct.new(:skill, :path, :line, :origin, keyword_init: true)

def fail!(message)
  warn(message)
  exit(1)
end

def normalize_path(token)
  value = token.to_s.strip
  value = value.split("=", 2).last if value.match?(/\A[A-Z][A-Z0-9_]*=/)
  value = value.gsub(/\A[`'"]+|[`'"]+\z/, "")
  value = value.sub(/\A[<>]+/, "").sub(/[>,;]+\z/, "")
  value = value.sub(/:\d+(?::\d+)?\z/, "")
  value = value.delete_prefix("./")
  value = value.sub(%r{/+\z}, "")
  return nil if value.empty? || value.match?(/\s/) || value.include?("://")
  return nil if value.start_with?("/", "~", "$")

  first = value.split("/", 2).first
  return value if value.start_with?("../orchestrator-integrations")
  return value if ROOT_NAMES.include?(value)
  return value if ROOT_PREFIXES.include?(first)
  return value if SKILL_PREFIXES.include?(first)

  nil
end

def candidates_for(skill, text)
  candidates = []
  in_fence = false
  shell_fence = false

  text.each_line.with_index(1) do |line, number|
    if (match = line.match(/^\s*```([^\s`]*)/))
      if in_fence
        in_fence = false
        shell_fence = false
      else
        in_fence = true
        shell_fence = SHELL_FENCES.include?(match[1].downcase)
      end
      next
    end

    if in_fence
      next unless shell_fence

      begin
        Shellwords.shellsplit(line).each do |token|
          path = normalize_path(token)
          next if path && !path.include?("/") && ROOT_PREFIXES.include?(path)
          candidates << Candidate.new(skill: skill, path: path, line: number, origin: "shell") if path
        end
      rescue ArgumentError
        # An intentionally incomplete command example is still scanned by the
        # inline-code pass; do not invent tokens from malformed shell syntax.
      end
      next
    end

    line.scan(/`([^`\n]+)`/).flatten.each do |token|
      path = normalize_path(token)
      candidates << Candidate.new(skill: skill, path: path, line: number, origin: "inline") if path
    end
  end

  candidates.uniq { |candidate| [candidate.path, candidate.line, candidate.origin] }
end

def skill_records(root)
  source = root.join(".claude/skills")
  records = Dir.glob(source.join("*/SKILL.md")).sort.map do |file|
    text = File.read(file)
    frontmatter = text.match(/\A---\s*\n(.*?)\n---\s*\n/m)&.captures&.first
    fail!("#{file}: missing YAML frontmatter") unless frontmatter
    metadata = YAML.safe_load(frontmatter)
    name = metadata["name"]&.strip
    description = metadata["description"]&.strip
    fail!("#{file}: frontmatter must contain one-line name and description") if name.to_s.empty? || description.to_s.empty?
    directory = File.basename(File.dirname(file))
    fail!("#{file}: name '#{name}' must equal directory '#{directory}'") unless name == directory
    { "name" => name, "description" => description, "file" => Pathname(file), "text" => text }
  end
  fail!("#{source}: no authoritative SKILL.md files found") if records.empty?
  duplicates = records.group_by { |record| record.fetch("name") }.select { |_name, rows| rows.length > 1 }.keys
  fail!("duplicate skill names: #{duplicates.join(', ')}") unless duplicates.empty?
  records
end

def render_registry(records)
  rows = records.sort_by { |record| record.fetch("name") }.map do |record|
    description = record.fetch("description").gsub("|", "\\|")
    "| `#{record.fetch('name')}` | #{description} |"
  end
  <<~MARKDOWN
    # Skills

    <!-- GENERATED by scripts/lib/skill_docs.rb; edit .claude/skills/*/SKILL.md instead. -->

    `.claude/skills/` is the single authoritative skill source. `.agents/skills/` and
    `.cursor/skills/` are symlink mirrors governed by
    `config/governance/skill-mirrors.json`.

    `scripts/qa/test-skill-mirror-integrity.sh` verifies mirror shape and readability,
    exact inventory coverage, and path references parsed from every skill. Repository
    and skill-relative paths must exist; generated-project templates, future outputs,
    and the optional companion repository require exact declarations in
    `config/governance/skill-path-scopes.json`.

    ## Inventory

    | Skill | Description |
    |-------|-------------|
    #{rows.join("\n")}
  MARKDOWN
end

def expanded_pattern(path)
  path.gsub(/<[^>]+>|\{[^}]+\}/, "*")
end

def existing_path?(base, path)
  expanded = expanded_pattern(path)
  if expanded.match?(GLOB_CHARS)
    !Dir.glob(base.join(expanded).to_s, File::FNM_EXTGLOB).empty?
  else
    base.join(expanded).exist?
  end
end

def load_declarations(root)
  policy_path = root.join("config/governance/skill-path-scopes.json")
  policy = JSON.parse(File.read(policy_path))
  declarations = policy.fetch("declarations")
  fail!("#{policy_path}: declarations must be an array") unless declarations.is_a?(Array)
  declarations
end

def validate_declaration!(root, declaration)
  required = %w[skill path scope reason]
  missing = required.reject { |key| declaration[key].is_a?(String) && !declaration[key].strip.empty? }
  fail!("invalid skill path declaration (missing #{missing.join(', ')}): #{declaration}") unless missing.empty?
  fail!("unknown skill path scope '#{declaration['scope']}'") unless SCOPES.include?(declaration["scope"])
  if declaration.fetch("path").match?(GLOB_CHARS)
    fail!("blanket skill path declaration is forbidden: #{declaration['skill']}:#{declaration['path']}")
  end
  fail!("skill path declaration reason is too short: #{declaration}") if declaration.fetch("reason").length < 12

  case declaration.fetch("scope")
  when "repo"
    target = declaration.fetch("target", declaration.fetch("path"))
    fail!("repo declaration target is missing: #{target}") unless existing_path?(root, target)
  when "skill-relative"
    target = declaration.fetch("target", declaration.fetch("path"))
    base = root.join(".claude/skills", declaration.fetch("skill"))
    fail!("skill-relative declaration target is missing: #{target}") unless existing_path?(base, target)
  when "template"
    target = declaration.fetch("target", "")
    prefix = ".claude/skills/project-bootstrap/assets/template/"
    fail!("template declaration target must be an exact project-bootstrap asset: #{target}") unless target.start_with?(prefix) && !target.match?(GLOB_CHARS)
    fail!("template declaration target is missing: #{target}") unless root.join(target).exist?
  when "output"
    target = declaration.fetch("target", "")
    fail!("output declaration target must be an exact existing parent directory: #{target}") if target.empty? || target.match?(GLOB_CHARS) || !root.join(target).directory?
  when "companion"
    repository = declaration.fetch("repository", "")
    expected = "../#{repository}"
    fail!("companion declaration must name its exact repository: #{declaration}") if repository.empty? || !declaration.fetch("path").start_with?(expected)
  end
end

def check_paths(root, records, dump: false)
  declarations = load_declarations(root)
  declarations.each { |declaration| validate_declaration!(root, declaration) }
  duplicate_keys = declarations.group_by { |row| [row["skill"], row["path"]] }.select { |_key, rows| rows.length > 1 }.keys
  fail!("duplicate skill path declarations: #{duplicate_keys.inspect}") unless duplicate_keys.empty?
  declared = declarations.to_h { |row| [[row.fetch("skill"), row.fetch("path")], row] }

  candidates = records.flat_map do |record|
    candidates_for(record.fetch("name"), record.fetch("text"))
  end
  observed = candidates.map { |candidate| [candidate.skill, candidate.path] }.uniq
  stale = declared.keys - observed
  fail!("stale skill path declarations (no parsed reference): #{stale.inspect}") unless stale.empty?

  errors = []
  classifications = []
  candidates.each do |candidate|
    declaration = declared[[candidate.skill, candidate.path]]
    if declaration
      classifications << [candidate, declaration.fetch("scope")]
      next
    end

    record = records.find { |item| item.fetch("name") == candidate.skill }
    skill_root = record.fetch("file").dirname
    if existing_path?(root, candidate.path)
      classifications << [candidate, "repo"]
    elsif SKILL_PREFIXES.include?(candidate.path.split("/", 2).first) && existing_path?(skill_root, candidate.path)
      classifications << [candidate, "skill-relative"]
    else
      errors << "#{record.fetch('file').relative_path_from(root)}:#{candidate.line}: #{candidate.path} (#{candidate.origin})"
    end
  end

  if dump
    classifications.sort_by { |candidate, scope| [candidate.skill, candidate.path, candidate.line] }.each do |candidate, scope|
      puts("#{candidate.skill}\t#{scope}\t#{candidate.path}\t#{candidate.line}\t#{candidate.origin}")
    end
  end
  fail!("unscoped or missing skill path references:\n  #{errors.uniq.join("\n  ")}") unless errors.empty?
end

mode = ARGV.shift
root = Pathname(ARGV.shift || Dir.pwd).expand_path
records = skill_records(root)

case mode
when "render-registry"
  print(render_registry(records))
when "check-registry"
  expected = render_registry(records)
  actual = File.read(root.join("SKILLS.md"))
  fail!("SKILLS.md differs from the authoritative skill inventory; run scripts/lib/skill_docs.rb render-registry > SKILLS.md") unless actual == expected
when "check-paths"
  check_paths(root, records)
when "dump-paths"
  check_paths(root, records, dump: true)
else
  fail!("usage: skill_docs.rb {render-registry|check-registry|check-paths|dump-paths} [repo-root]")
end
