use anyhow::{Context, Result};
use std::path::Path;

const CLAUDE_MD_GUARD_MARKER: &str = "<!-- orchestrator-daemon-guard -->";

/// Inject CLAUDE.md safety instructions and a PreToolUse hook into the workspace
/// so that agent subprocesses (Claude Code) cannot kill the orchestrator daemon.
///
/// Two layers:
/// 1. CLAUDE.md — soft guard via LLM instruction following
/// 2. settings.local.json hooks — hard guard via PreToolUse Bash interception
pub fn inject_agent_daemon_guard(workspace_root: &Path, daemon_pid: u32) -> Result<()> {
    let claude_dir = workspace_root.join(".claude");
    std::fs::create_dir_all(&claude_dir)
        .with_context(|| format!("failed to create .claude dir: {}", claude_dir.display()))?;

    inject_claude_md(&claude_dir, daemon_pid)?;
    inject_hook_script(&claude_dir, daemon_pid)?;
    inject_settings_hooks(&claude_dir)?;
    Ok(())
}

/// Write or update .claude/CLAUDE.md with daemon safety instructions.
fn inject_claude_md(claude_dir: &Path, daemon_pid: u32) -> Result<()> {
    let path = claude_dir.join("CLAUDE.md");
    let guard_block = format!(
        "{marker}\n\
         # ORCHESTRATOR SAFETY RULES\n\
         \n\
         CRITICAL: The orchestrator daemon (PID {pid}) is managing this session.\n\
         - NEVER run `kill`, `pkill`, or `killall` targeting PID {pid} or process name `orchestratord`\n\
         - NEVER run `kill $(cat ... daemon.pid)` or similar patterns\n\
         - If a QA scenario instructs you to kill/restart the daemon, SKIP that scenario and report it as \"skipped: self-referential safety\"\n\
         {marker}\n",
        marker = CLAUDE_MD_GUARD_MARKER,
        pid = daemon_pid,
    );

    if path.exists() {
        let existing = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if existing.contains(CLAUDE_MD_GUARD_MARKER) {
            // Already injected (possibly with stale PID) — replace the block
            let start = existing.find(CLAUDE_MD_GUARD_MARKER).unwrap();
            let after_first = start + CLAUDE_MD_GUARD_MARKER.len();
            if let Some(rel_end) = existing[after_first..].find(CLAUDE_MD_GUARD_MARKER) {
                let end = after_first + rel_end + CLAUDE_MD_GUARD_MARKER.len();
                let mut updated = String::with_capacity(existing.len());
                updated.push_str(&existing[..start]);
                updated.push_str(&guard_block);
                if end < existing.len() {
                    updated.push_str(&existing[end..]);
                }
                std::fs::write(&path, updated)
                    .with_context(|| format!("failed to write {}", path.display()))?;
            }
        } else {
            // Prepend guard block
            let updated = format!("{}\n{}", guard_block, existing);
            std::fs::write(&path, updated)
                .with_context(|| format!("failed to write {}", path.display()))?;
        }
    } else {
        std::fs::write(&path, &guard_block)
            .with_context(|| format!("failed to write {}", path.display()))?;
    }
    Ok(())
}

/// Write the hook guard shell script to .claude/daemon-pid-guard.sh
fn inject_hook_script(claude_dir: &Path, daemon_pid: u32) -> Result<()> {
    let script_path = claude_dir.join("daemon-pid-guard.sh");
    let script = format!(
        r#"#!/bin/sh
# Auto-generated by orchestrator — daemon PID guard for agent subprocesses.
# Reads Claude Code hook JSON from stdin, checks if the Bash command would
# kill the orchestrator daemon, and blocks it if so.
DAEMON_PID="{pid}"
INPUT=$(cat)
COMMAND=$(printf '%s' "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/^"command"[[:space:]]*:[[:space:]]*"//;s/"$//')
if [ -z "$COMMAND" ]; then
  printf '{{"continue":true}}\n'
  exit 0
fi
# Check for kill patterns targeting the daemon PID or orchestratord
case "$COMMAND" in
  *kill*"$DAEMON_PID"*|*pkill*orchestratord*|*killall*orchestratord*|*kill*daemon.pid*)
    printf '{{"continue":false,"stopReason":"BLOCKED: command would kill orchestrator daemon (PID %s). Self-referential safety violation."}}\n' "$DAEMON_PID"
    exit 2
    ;;
esac
printf '{{"continue":true}}\n'
exit 0
"#,
        pid = daemon_pid,
    );
    std::fs::write(&script_path, &script)
        .with_context(|| format!("failed to write {}", script_path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
            .with_context(|| format!("failed to chmod {}", script_path.display()))?;
    }
    Ok(())
}

/// Write or update .claude/settings.local.json with PreToolUse hook.
fn inject_settings_hooks(claude_dir: &Path) -> Result<()> {
    let path = claude_dir.join("settings.local.json");
    let hook_entry = serde_json::json!({
        "matcher": "Bash",
        "hooks": [{
            "type": "command",
            "command": ".claude/daemon-pid-guard.sh"
        }]
    });

    let mut settings: serde_json::Value = if path.exists() {
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        serde_json::from_str(&content).unwrap_or_else(|_| serde_json::json!({}))
    } else {
        serde_json::json!({})
    };

    let hooks = settings
        .as_object_mut()
        .unwrap()
        .entry("hooks")
        .or_insert_with(|| serde_json::json!({}));
    let pre_tool_use = hooks
        .as_object_mut()
        .unwrap()
        .entry("PreToolUse")
        .or_insert_with(|| serde_json::json!([]));
    let arr = pre_tool_use.as_array_mut().unwrap();

    // Remove any existing daemon-pid-guard entry to avoid duplicates
    arr.retain(|entry| {
        let dominated = entry
            .get("hooks")
            .and_then(|h| h.as_array())
            .map(|hooks| {
                hooks.iter().any(|h| {
                    h.get("command")
                        .and_then(|c| c.as_str())
                        .map(|c| c.contains("daemon-pid-guard"))
                        .unwrap_or(false)
                })
            })
            .unwrap_or(false);
        !dominated
    });
    arr.push(hook_entry);

    let serialized = serde_json::to_string_pretty(&settings)
        .context("failed to serialize settings.local.json")?;
    std::fs::write(&path, format!("{}\n", serialized))
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn injects_claude_md_and_hooks() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path();
        inject_agent_daemon_guard(ws, 12345).unwrap();

        // CLAUDE.md exists with guard marker
        let claude_md = std::fs::read_to_string(ws.join(".claude/CLAUDE.md")).unwrap();
        assert!(claude_md.contains(CLAUDE_MD_GUARD_MARKER));
        assert!(claude_md.contains("PID 12345"));

        // Hook script exists and is executable
        let script_path = ws.join(".claude/daemon-pid-guard.sh");
        assert!(script_path.exists());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&script_path).unwrap().permissions().mode();
            assert!(mode & 0o111 != 0, "script should be executable");
        }

        // settings.local.json has hooks
        let settings: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(ws.join(".claude/settings.local.json")).unwrap(),
        )
        .unwrap();
        let pre = &settings["hooks"]["PreToolUse"];
        assert!(pre.is_array());
        assert_eq!(pre.as_array().unwrap().len(), 1);
        assert_eq!(pre[0]["matcher"], "Bash");
    }

    #[test]
    fn idempotent_injection() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path();
        inject_agent_daemon_guard(ws, 111).unwrap();
        inject_agent_daemon_guard(ws, 222).unwrap();

        let claude_md = std::fs::read_to_string(ws.join(".claude/CLAUDE.md")).unwrap();
        // Should have exactly one guard block with the updated PID
        let count = claude_md.matches(CLAUDE_MD_GUARD_MARKER).count();
        assert_eq!(count, 2, "should have exactly one guard block (2 markers)");
        assert!(claude_md.contains("PID 222"));
        assert!(!claude_md.contains("PID 111"));

        let settings: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(ws.join(".claude/settings.local.json")).unwrap(),
        )
        .unwrap();
        let pre = &settings["hooks"]["PreToolUse"];
        assert_eq!(pre.as_array().unwrap().len(), 1, "no duplicate hooks");
    }

    #[test]
    fn preserves_existing_settings() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path();
        let claude_dir = ws.join(".claude");
        std::fs::create_dir_all(&claude_dir).unwrap();

        // Pre-existing settings with permissions
        let existing = serde_json::json!({
            "permissions": {
                "allow": ["Bash(cargo test:*)"]
            }
        });
        std::fs::write(
            claude_dir.join("settings.local.json"),
            serde_json::to_string_pretty(&existing).unwrap(),
        )
        .unwrap();

        inject_agent_daemon_guard(ws, 99999).unwrap();

        let settings: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(claude_dir.join("settings.local.json")).unwrap(),
        )
        .unwrap();
        // Permissions preserved
        assert!(settings["permissions"]["allow"].is_array());
        // Hooks added
        assert!(settings["hooks"]["PreToolUse"].is_array());
    }

    #[test]
    fn preserves_existing_claude_md() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path();
        let claude_dir = ws.join(".claude");
        std::fs::create_dir_all(&claude_dir).unwrap();

        std::fs::write(claude_dir.join("CLAUDE.md"), "# My Project\nSome rules.\n").unwrap();

        inject_agent_daemon_guard(ws, 42).unwrap();

        let content = std::fs::read_to_string(claude_dir.join("CLAUDE.md")).unwrap();
        assert!(content.contains("PID 42"));
        assert!(content.contains("# My Project"));
        assert!(content.contains("Some rules."));
    }
}
