#[derive(Clone)]
pub struct NewCommandRun {
    pub id: String,
    pub task_item_id: String,
    pub phase: String,
    pub command: String,
    pub cwd: String,
    pub workspace_id: String,
    pub agent_id: String,
    pub exit_code: i64,
    pub stdout_path: String,
    pub stderr_path: String,
    pub started_at: String,
    pub ended_at: String,
    pub interrupted: i64,
    pub output_json: String,
    pub artifacts_json: String,
    pub confidence: Option<f32>,
    pub quality_score: Option<f32>,
    pub validation_status: String,
    pub session_id: Option<String>,
    pub machine_output_source: String,
    pub output_json_path: Option<String>,
}
